### PR TITLE
Create base rubocop file for 1-59

### PR DESCRIPTION
**Pull request by rebeccafae**
**_Summary and description of changes_**:
Create the base rubocop file (rubocop and rails cops) for version 1.59.0
The cops should align with the decisions made in [this doc](https://qcentrix.atlassian.net/wiki/spaces/ENG/pages/2067562728/Rubocop+1.23+to+1.56.3)

merge AFTER https://github.com/codeclimate/codeclimate-rubocop/pull/363 (could be merged first, but should not be used until the codeclimate channel is merged)

### CODE REVIEW

**Comment by rebeccafae** [comment]
This can be reviewed now, or we can wait until we have the files for all the cops (rspec, graphql, and performance). Your choice!

**Review by jessigu — APPROVED** [review]
LGTM
confirmed declarations here match what we discussed 🎉

**Comment by albertski** [comment]
@rebeccafae What was the reason we were waiting for https://github.com/codeclimate/codeclimate-rubocop/pull/363? It seems like they updated that PR to be for Rubocop 1.60.1.

**Comment by rebeccafae** [comment]
> @rebeccafae What was the reason we were waiting for [codeclimate/codeclimate-rubocop#363](https://github.com/codeclimate/codeclimate-rubocop/pull/363)? It seems like they updated that PR to be for Rubocop 1.60.1.

It is not merged yet and therefore not available. The author of that PR keeps updating it as robocop updates to keep it current until it merges. He did the same thing with the last PR he made. I want to wait to merge this one until that is merged so we can also make any updates needed if there are any. So far with his updates there hasn't been anything that changes this file, though I haven't looked at the most recent one yet, it's on my list to do.

Edit: I reviewed the changelog and we are still good with this PR as is, but I'll change the file name once I know the version on the other one is not updating any more.

**Comment by rebeccafae** [comment]
Closing in favor of #10

**Pull request closed without merging**
